/**
 * data.js — Mayurbhanj Tourist Spots Dataset
 * Coordinates verified for Mayurbhanj district, Odisha, India
 */

const TOURIST_SPOTS = [
  {
    id: 1,
    name: "Similipal National Park",
    category: "nature",
    icon: "🐅",
    emoji: "🌿",
    image: "images/similipal.png",
    lat: 21.7500, lng: 86.3300,
    location: "Baripada, Mayurbhanj",
    shortDesc: "UNESCO Biosphere Reserve & Tiger Reserve",
    description: "Similipal is one of India's premier tiger reserves and a UNESCO designated Biosphere Reserve covering over 2,750 sq km. It is home to Royal Bengal Tigers, Asian Elephants, leopards, and over 300 species of birds. The park is adorned with dense sal forests, grassy meadows, and spectacular waterfalls.",
    bestTime: "Nov – June",
    entryFee: "₹40 Indian / ₹600 Foreign",
    distance: "70 km from Baripada",
    type: ["Wildlife", "Nature", "UNESCO"],
    tags: ["Tiger Reserve", "Biosphere Reserve"],
    highlight: "⭐ UNESCO Biosphere Reserve",
  },
  {
    id: 2,
    name: "Barehipani Waterfall",
    category: "waterfall",
    icon: "💧",
    emoji: "🌊",
    image: "images/barehipani.png",
    lat: 21.9000, lng: 86.3500,
    location: "Inside Similipal, Mayurbhanj",
    shortDesc: "One of India's highest waterfalls at ~400m",
    description: "Barehipani is one of the highest waterfalls in India, plunging approximately 400 meters from a plateau into a deep gorge below. Located inside the Similipal National Park, this magnificent two-tiered waterfall is surrounded by lush forested hills and offers a breathtaking spectacle, especially during and after the monsoon season.",
    bestTime: "Oct – Feb",
    entryFee: "Park entry fee applies",
    distance: "Inside Similipal Park",
    type: ["Waterfall", "Nature"],
    tags: ["Tallest Waterfall", "Scenic"],
    highlight: "⭐ 400m Drop — India's Highest",
  },
  {
    id: 3,
    name: "Joranda Waterfall",
    category: "waterfall",
    icon: "💧",
    emoji: "🌊",
    image: "images/joranda.png",
    lat: 21.7980, lng: 86.3700,
    location: "Inside Similipal, Mayurbhanj",
    shortDesc: "Majestic single-drop waterfall of ~181m",
    description: "Joranda Waterfall is a spectacular single-drop waterfall with a plunge of approximately 181 meters, making it one of the tallest single-drop waterfalls in India. Surrounded by pristine forest inside Similipal National Park, the roaring cascade creates a misty atmosphere that is hauntingly beautiful and serene.",
    bestTime: "Oct – Mar",
    entryFee: "Park entry fee applies",
    distance: "Inside Similipal Park",
    type: ["Waterfall", "Nature"],
    tags: ["Single Drop", "Scenic"],
    highlight: "⭐ 181m Single-Drop Plunge",
  },
  {
    id: 4,
    name: "Devkund Waterfall",
    category: "waterfall",
    icon: "💧",
    emoji: "🌈",
    image: "images/devkund.png",
    lat: 21.6820, lng: 86.5200,
    location: "Shyampur, Mayurbhanj",
    shortDesc: "Scenic waterfall with Maa Ambika Temple",
    description: "Devkund is a picturesque waterfall and one of the most popular day-trip destinations in Mayurbhanj. The waterfall is set amidst lush greenery and at its base sits the revered Maa Ambika Temple, making it a pilgrimage site as well as a natural attraction. The combined natural beauty and spiritual significance make this a unique spot.",
    bestTime: "Oct – Mar",
    entryFee: "Free",
    distance: "45 km from Baripada",
    type: ["Waterfall", "Religious"],
    tags: ["Temple", "Picnic Spot"],
    highlight: "⭐ Maa Ambika Temple + Falls",
  },
  {
    id: 5,
    name: "Sitakund Waterfall",
    category: "waterfall",
    icon: "💧",
    emoji: "🌿",
    image: "images/sitakund.png",
    lat: 21.8500, lng: 86.4800,
    location: "Near Pithabata, Mayurbhanj",
    shortDesc: "Beautiful picnic waterfall near Similipal gate",
    description: "Sitakund Waterfall is a beautiful and easily accessible waterfall near the Pithabata entry gate of Similipal. It is one of the most scenic picnic spots in the district, surrounded by forests and offering a refreshing escape. The waterfall cascades over rocky terrain making it an ideal destination for nature lovers and trekkers.",
    bestTime: "Oct – Mar",
    entryFee: "Free",
    distance: "Near Pithabata Gate",
    type: ["Waterfall", "Nature"],
    tags: ["Picnic Spot", "Trekking"],
    highlight: "⭐ Perfect Picnic Destination",
  },
  {
    id: 6,
    name: "Khiching Temple & Museum",
    category: "heritage",
    icon: "🏛️",
    emoji: "🏺",
    image: "images/khiching.png",
    lat: 21.6200, lng: 86.2850,
    location: "Khiching, Mayurbhanj",
    shortDesc: "Ancient Kichakeswari Temple & archaeological museum",
    description: "Khiching is home to the famous Kichakeswari Temple dedicated to Goddess Kichakeswari, which dates back several centuries. The Archaeological Museum here houses a remarkable collection of sculptures, inscriptions, and artifacts from the region's ancient heritage. The temple architecture and the rare museum collection make this one of the most important heritage destinations in Odisha.",
    bestTime: "Year Round",
    entryFee: "Museum: ₹15",
    distance: "95 km from Baripada",
    type: ["Heritage", "Temple", "Museum"],
    tags: ["Ancient Temple", "Museum"],
    highlight: "⭐ Rare Archaeological Museum",
  },
  {
    id: 7,
    name: "Belgadia Palace",
    category: "heritage",
    icon: "🏰",
    emoji: "👑",
    image: "images/belgadia.png",
    lat: 21.9290, lng: 86.7370,
    location: "Baripada, Mayurbhanj",
    shortDesc: "Historic royal palace of the Mayurbhanj Kingdom",
    description: "Belgadia Palace is the magnificent former residence of the Maharajas of Mayurbhanj, known for its blend of colonial and traditional architectural styles. The palace is a testament to the rich royal heritage of the region and has been partially converted into a heritage hotel. Its grandeur and history attract visitors interested in the storied past of Odisha's princely states.",
    bestTime: "Oct – Feb",
    entryFee: "Varies",
    distance: "In Baripada city",
    type: ["Heritage", "Palace"],
    tags: ["Royal Heritage", "Architecture"],
    highlight: "⭐ Mayurbhanj Royal Heritage",
  },
  {
    id: 8,
    name: "Haribaldev Temple",
    category: "religious",
    icon: "🛕",
    emoji: "🙏",
    image: "images/haribaldev.png",
    lat: 21.9340, lng: 86.7260,
    location: "Baripada, Mayurbhanj",
    shortDesc: "Historic 1575 AD Jagannath temple in Baripada",
    description: "The Haribaldev Temple in Baripada is one of the most revered religious sites in Mayurbhanj. Built in 1575 AD, this historic Jagannath temple hosts the famous Baripada Rath Yatra (Chariot Festival), which rivals that of Puri in grandeur. The temple's spiritual significance and the annual Rath Yatra attract pilgrims and tourists from across India.",
    bestTime: "Year Round",
    entryFee: "Free",
    distance: "In Baripada city",
    type: ["Religious", "Temple"],
    tags: ["Jagannath Temple", "Rath Yatra"],
    highlight: "⭐ Famous Rath Yatra Festival",
  },
  {
    id: 9,
    name: "Ramatirtha & Crocodile Centre",
    category: "wildlife",
    icon: "🐊",
    emoji: "🌾",
    image: "images/ramatirtha.png",
    lat: 21.9700, lng: 86.5800,
    location: "Ramatirtha, Mayurbhanj",
    shortDesc: "Mugger crocodile research and conservation center",
    description: "Ramatirtha is a scenic spot on the Budhabalanga River known for its Mugger Crocodile Research Centre, one of the few such facilities in Odisha. The center undertakes conservation and research work for the endangered mugger crocodile species. The tranquil riverine environment and the opportunity to observe crocodiles in their natural setting make this a unique wildlife destination.",
    bestTime: "Oct – Mar",
    entryFee: "Nominal fee",
    distance: "32 km from Baripada",
    type: ["Wildlife", "Conservation"],
    tags: ["Crocodile", "Research Centre"],
    highlight: "⭐ Rare Mugger Crocodile Habitat",
  },
  {
    id: 10,
    name: "Bhimkund",
    category: "religious",
    icon: "🛕",
    emoji: "💫",
    image: "images/bhimkund.png",
    lat: 21.5900, lng: 86.6300,
    location: "Betnoti, Mayurbhanj",
    shortDesc: "Sacred deep natural pool in the Vaitarani River",
    description: "Bhimkund is a sacred and mysterious natural kund (pool) formed in the Vaitarani River, believed to be bottomless according to local mythology. According to legend, the Pandava Bhima created this kund by striking the ground with his mace. The site holds great religious significance and is visited by thousands of devotees, especially on auspicious occasions.",
    bestTime: "Oct – Mar",
    entryFee: "Free",
    distance: "70 km from Baripada",
    type: ["Religious", "Nature"],
    tags: ["Sacred Pool", "Mythology"],
    highlight: "⭐ Mythological 'Bottomless' Pool",
  },
  {
    id: 11,
    name: "Gurguria Orchidarium",
    category: "nature",
    icon: "🌸",
    emoji: "🌺",
    image: "images/gurguria.png",
    lat: 21.8200, lng: 86.4200,
    location: "Gurguria, Similipal",
    shortDesc: "Beautiful orchid garden inside Similipal",
    description: "The Gurguria Orchidarium inside Similipal National Park is a renowned center for orchid conservation and research. Similipal is known to be rich in diverse orchid species, and Gurguria serves as the main visitor reception area within the core zone. The orchidarium showcases a stunning variety of these delicate flowers along with a scenic forest environment.",
    bestTime: "Mar – May",
    entryFee: "Park entry fee",
    distance: "Inside Similipal (Core Zone)",
    type: ["Nature", "Flora"],
    tags: ["Orchids", "Forest"],
    highlight: "⭐ Rare Wild Orchid Collection",
  },
  {
    id: 12,
    name: "Baripada City",
    category: "heritage",
    icon: "🏙️",
    emoji: "🌺",
    image: "images/baripada.png",
    lat: 21.9329, lng: 86.7319,
    location: "Baripada, Mayurbhanj HQ",
    shortDesc: "District capital — gateway to Similipal",
    description: "Baripada is the district headquarters and cultural capital of Mayurbhanj. Known for the grand Baripada Rath Yatra, the Shyam Sundar Museum, and traditional Chaiti Ghoda dance, the city offers a perfect blend of culture, history, and modern amenities. It serves as the primary base for tourists exploring the entire district.",
    bestTime: "Year Round",
    entryFee: "Free",
    distance: "0 km (District HQ)",
    type: ["Heritage", "Culture", "City"],
    tags: ["Rath Yatra", "Cultural Hub"],
    highlight: "⭐ Gateway to Mayurbhanj",
  },
  {
    id: 13,
    name: "Kichakeswari Temple",
    category: "religious",
    icon: "🛕",
    emoji: "🌸",
    image: "images/Kichakeswari Temple.png",
    lat: 21.927778, lng: 85.832222,
    location: " Khiching village in odisha",
    shortDesc: "located in the village of Khiching, situated in the Sukruli block of the Mayurbhanj district in the northern part of Odisha",
    description: "The Kichakeswari Temple is an architectural masterpiece located in Khiching, the ancient capital of the Bhanja rulers, within the Mayurbhanj district of Odisha. Dedicated to Goddess Chamunda (Kali), it serves as one of the most culturally significant shrines in northern Odisha.",
    bestTime: "Year Round",
    entryFee: "Free",
    distance: "8.2 km from baripada",
    type: ["Religious", "Heritage", "Temple"],
    tags: ["Goddess Chamunda (Kali)", "Bhanja Dynasty"],
    highlight: "⭐ Goddess Chamunda (Kali) Temple",
  }
];

// Category metadata
const CATEGORY_META = {
  nature: { label: "Nature", color: "#22c55e", bg: "rgba(34,197,94,0.15)", icon: "fa-tree" },
  waterfall: { label: "Waterfall", color: "#38bdf8", bg: "rgba(56,189,248,0.15)", icon: "fa-water" },
  heritage: { label: "Heritage", color: "#f59e0b", bg: "rgba(245,158,11,0.15)", icon: "fa-landmark" },
  religious: { label: "Temple", color: "#a855f7", bg: "rgba(168,85,247,0.15)", icon: "fa-place-of-worship" },
  wildlife: { label: "Wildlife", color: "#f97316", bg: "rgba(249,115,22,0.15)", icon: "fa-paw" },
};
